// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebDispositivosMqtt.Data.Models;

public partial class Alarm
{
    public int Id { get; set; }

    public Guid DeviceId { get; set; }

    public string Type { get; set; }

    public string Description { get; set; }

    public byte Severity { get; set; }

    public DateTime CreatedAtUtc { get; set; }

    public virtual ICollection<AlarmRead> AlarmReads { get; set; } = new List<AlarmRead>();

    public virtual Device Device { get; set; }
}