// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebDispositivosMqtt.Data.Models;

public partial class AlarmRead
{
    public long Id { get; set; }

    public int AlarmId { get; set; }

    public string UserId { get; set; }

    public DateTime ReadAtUtc { get; set; }

    public DateTime? DismissedAtUtc { get; set; }

    public virtual Alarm Alarm { get; set; }

    public virtual AspNetUser User { get; set; }
}