// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebDispositivosMqtt.Data.Models;

public partial class BatteryType
{
    public int Id { get; set; }

    public string Name { get; set; }

    public decimal? ChargingMinV { get; set; }

    public decimal GoodMinV { get; set; }

    public decimal LowMinV { get; set; }

    public bool IsDefault { get; set; }

    public virtual ICollection<ChlorinatorConfig> ChlorinatorConfigs { get; set; } = new List<ChlorinatorConfig>();
}