// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebDispositivosMqtt.Data.Models;

public partial class ChlorinatorDailySummary
{
    public int Id { get; set; }

    public Guid DeviceId { get; set; }

    public DateOnly Day { get; set; }

    public int DoseCount { get; set; }

    public int TurnCount { get; set; }

    public int? ResetPowerOn { get; set; }

    public int? ResetSoftware { get; set; }

    public int? ResetPanic { get; set; }

    public int? ResetWatchdog { get; set; }

    public int? ResetBrownout { get; set; }

    public int? ResetOther { get; set; }

    public DateTime UpdatedAtUtc { get; set; }

    public virtual Device Device { get; set; }
}