// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebDispositivosMqtt.Data.Models;

public partial class ChlorinatorBattery
{
    public long Id { get; set; }

    public Guid DeviceId { get; set; }

    public DateTime TsUtc { get; set; }

    public decimal VoltageV { get; set; }

    public DateTime CreatedAtUtc { get; set; }

    public virtual Device Device { get; set; }
}