// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebDispositivosMqtt.Data.Models;

public partial class CloradorSecuencium
{
    public int Id { get; set; }

    public Guid DeviceId { get; set; }

    public DateTime Ts { get; set; }

    public int Vueltas { get; set; }

    public string TriggerType { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual Device Device { get; set; }
}