// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebDispositivosMqtt.Data.Models;

public partial class CloradorResumenDiario
{
    public int Id { get; set; }

    public Guid DeviceId { get; set; }

    public DateOnly Dia { get; set; }

    public int SecTotal { get; set; }

    public int VueltasTotal { get; set; }

    public DateTime UpdatedAt { get; set; }

    public virtual Device Device { get; set; }
}