// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebDispositivosMqtt.Data.Models;

public partial class Device
{
    public Guid DeviceId { get; set; }

    public string MacAddress { get; set; }

    public string Name { get; set; }

    public DateTime RegisteredAtUtc { get; set; }

    public string RegisteredByUserId { get; set; }

    public bool IsEnabled { get; set; }

    public string MqttCredential { get; set; }

    public DateTime? ProvisioningExpiresAt { get; set; }

    public bool IsDelivered { get; set; }

    public int? DeviceTypeId { get; set; }

    public virtual ICollection<Alarm> Alarms { get; set; } = new List<Alarm>();

    public virtual ICollection<CloradorResumenDiario> CloradorResumenDiarios { get; set; } = new List<CloradorResumenDiario>();

    public virtual ICollection<CloradorSecuencium> CloradorSecuencia { get; set; } = new List<CloradorSecuencium>();

    public virtual DeviceType DeviceType { get; set; }

    public virtual AspNetUser RegisteredByUser { get; set; }

    public virtual ICollection<UserDevice> UserDevices { get; set; } = new List<UserDevice>();
}