// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebDispositivosMqtt.Data.Models;

public partial class DeviceType
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public string TelemetrySp { get; set; }

    public virtual ICollection<Device> Devices { get; set; } = new List<Device>();
}