// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebDispositivosMqtt.Data.Models;

public partial class FcmToken
{
    public int Id { get; set; }

    public string UserId { get; set; }

    public string Token { get; set; }

    public DateTime CreatedAtUtc { get; set; }

    public DateTime LastUsedAtUtc { get; set; }

    public virtual AspNetUser User { get; set; }
}