// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebDispositivosMqtt.Data.Models;

public partial class TelemetryLog
{
    public int Id { get; set; }

    public Guid? DeviceId { get; set; }

    public string Topic { get; set; }

    public string Payload { get; set; }

    public bool Processed { get; set; }

    public string ErrorMessage { get; set; }

    public DateTime ReceivedAtUtc { get; set; }
}