// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebDispositivosMqtt.Data.Models;

public partial class UserDevice
{
    public int UserDeviceId { get; set; }

    public string UserId { get; set; }

    public Guid DeviceId { get; set; }

    public virtual Device Device { get; set; }

    public virtual AspNetUser User { get; set; }
}