// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using WebDispositivosMqtt.Data.Models;

namespace WebDispositivosMqtt.Data;

public partial class DatabaseContext : DbContext
{
    public DatabaseContext(DbContextOptions<DatabaseContext> options)
        : base(options)
    {
    }

    public virtual DbSet<AspNetUser> AspNetUsers { get; set; }

    public virtual DbSet<CloradorResumenDiario> CloradorResumenDiarios { get; set; }

    public virtual DbSet<CloradorSecuencium> CloradorSecuencia { get; set; }

    public virtual DbSet<Device> Devices { get; set; }

    public virtual DbSet<DeviceType> DeviceTypes { get; set; }

    public virtual DbSet<RefreshToken> RefreshTokens { get; set; }

    public virtual DbSet<TelemetryLog> TelemetryLogs { get; set; }

    public virtual DbSet<UserDevice> UserDevices { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.UseCollation("Latin1_General_100_CI_AS_SC");

        modelBuilder.Entity<AspNetUser>(entity =>
        {
            entity.ToTable("AspNetUsers", "identity");

            entity.HasIndex(e => e.NormalizedEmail, "EmailIndex");

            entity.HasIndex(e => e.NormalizedUserName, "UserNameIndex")
                .IsUnique()
                .HasFilter("([NormalizedUserName] IS NOT NULL)");

            entity.Property(e => e.Email).HasMaxLength(256);
            entity.Property(e => e.NormalizedEmail).HasMaxLength(256);
            entity.Property(e => e.NormalizedUserName).HasMaxLength(256);
            entity.Property(e => e.UserName).HasMaxLength(256);
        });

        modelBuilder.Entity<CloradorResumenDiario>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Clorador__3214EC074C55709B");

            entity.ToTable("CloradorResumenDiario");

            entity.HasIndex(e => new { e.DeviceId, e.Dia }, "UQ_CloradorResumenDiario_Device_Dia").IsUnique();

            entity.Property(e => e.UpdatedAt).HasDefaultValueSql("(getutcdate())");

            entity.HasOne(d => d.Device).WithMany(p => p.CloradorResumenDiarios)
                .HasForeignKey(d => d.DeviceId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_CloradorResumenDiario_Device");
        });

        modelBuilder.Entity<CloradorSecuencium>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Clorador__3214EC07DEE0121E");

            entity.HasIndex(e => new { e.DeviceId, e.Ts }, "IX_CloradorSecuencia_DeviceId_Ts").IsDescending(false, true);

            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getutcdate())");
            entity.Property(e => e.TriggerType).HasMaxLength(20);

            entity.HasOne(d => d.Device).WithMany(p => p.CloradorSecuencia)
                .HasForeignKey(d => d.DeviceId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_CloradorSecuencia_Device");
        });

        modelBuilder.Entity<Device>(entity =>
        {
            entity.HasKey(e => e.DeviceId).HasName("PK_Device");

            entity.HasIndex(e => e.MacAddress, "UX_Device_MacAddress").IsUnique();

            entity.Property(e => e.DeviceId).HasDefaultValueSql("(newid())", "DF_Device_DeviceId");
            entity.Property(e => e.IsEnabled).HasDefaultValue(true, "DF_Device_IsEnable");
            entity.Property(e => e.MacAddress)
                .IsRequired()
                .HasMaxLength(12)
                .IsUnicode(false)
                .IsFixedLength();
            entity.Property(e => e.MqttCredential)
                .HasMaxLength(500)
                .IsUnicode(false);
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.ProvisioningExpiresAt).HasColumnType("datetime");
            entity.Property(e => e.RegisteredAtUtc)
                .HasPrecision(0)
                .HasDefaultValueSql("(sysutcdatetime())", "DF_Device_RegisteredAtUtc");
            entity.Property(e => e.RegisteredByUserId)
                .IsRequired()
                .HasMaxLength(450);

            entity.HasOne(d => d.DeviceType).WithMany(p => p.Devices)
                .HasForeignKey(d => d.DeviceTypeId)
                .HasConstraintName("FK_Devices_DeviceType");

            entity.HasOne(d => d.RegisteredByUser).WithMany(p => p.Devices)
                .HasForeignKey(d => d.RegisteredByUserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Device_AspNetUsers_RegisteredBy");
        });

        modelBuilder.Entity<DeviceType>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__DeviceTy__3214EC07D0000D4E");

            entity.HasIndex(e => e.Name, "UQ_DeviceTypes_Name").IsUnique();

            entity.Property(e => e.Description).HasMaxLength(200);
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.TelemetrySp).HasMaxLength(100);
        });

        modelBuilder.Entity<RefreshToken>(entity =>
        {
            entity.HasIndex(e => e.UserId, "IX_RefreshTokens_UserId");

            entity.HasIndex(e => e.Token, "UQ_RefreshTokens_Token").IsUnique();

            entity.Property(e => e.CreatedAtUtc)
                .HasPrecision(0)
                .HasDefaultValueSql("(sysutcdatetime())", "DF_RefreshTokens_CreatedAtUtc");
            entity.Property(e => e.ExpiresAtUtc).HasPrecision(0);
            entity.Property(e => e.RevokedAtUtc).HasPrecision(0);
            entity.Property(e => e.Token)
                .IsRequired()
                .HasMaxLength(500);
            entity.Property(e => e.UserId).IsRequired();

            entity.HasOne(d => d.User).WithMany(p => p.RefreshTokens)
                .HasForeignKey(d => d.UserId)
                .HasConstraintName("FK_RefreshTokens_AspNetUsers");
        });

        modelBuilder.Entity<TelemetryLog>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Telemetr__3214EC07D1A9E0D4");

            entity.ToTable("TelemetryLog");

            entity.HasIndex(e => e.Processed, "IX_TelemetryLog_Processed");

            entity.HasIndex(e => e.ReceivedAtUtc, "IX_TelemetryLog_ReceivedAtUtc").IsDescending();

            entity.Property(e => e.ErrorMessage).HasMaxLength(2000);
            entity.Property(e => e.Payload).IsRequired();
            entity.Property(e => e.ReceivedAtUtc).HasDefaultValueSql("(getutcdate())");
            entity.Property(e => e.Topic)
                .IsRequired()
                .HasMaxLength(500);
        });

        modelBuilder.Entity<UserDevice>(entity =>
        {
            entity.HasIndex(e => new { e.UserId, e.DeviceId }, "UQ_UserDevices_User_Device").IsUnique();

            entity.Property(e => e.UserId).IsRequired();

            entity.HasOne(d => d.Device).WithMany(p => p.UserDevices)
                .HasForeignKey(d => d.DeviceId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_UserDevices_Devices");

            entity.HasOne(d => d.User).WithMany(p => p.UserDevices)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_UserDevices_AspNetUsers");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}