// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using WebDispositivosMqtt.Data.Models;

namespace WebDispositivosMqtt.Data;

public partial class DatabaseContext : DbContext
{
    public DatabaseContext(DbContextOptions<DatabaseContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Alarm> Alarms { get; set; }

    public virtual DbSet<AlarmRead> AlarmReads { get; set; }

    public virtual DbSet<AspNetUser> AspNetUsers { get; set; }

    public virtual DbSet<BatteryType> BatteryTypes { get; set; }

    public virtual DbSet<ChlorinatorBattery> ChlorinatorBatteries { get; set; }

    public virtual DbSet<ChlorinatorConfig> ChlorinatorConfigs { get; set; }

    public virtual DbSet<ChlorinatorDailySummary> ChlorinatorDailySummaries { get; set; }

    public virtual DbSet<ChlorinatorDose> ChlorinatorDoses { get; set; }

    public virtual DbSet<ChlorinatorLevel> ChlorinatorLevels { get; set; }

    public virtual DbSet<Device> Devices { get; set; }

    public virtual DbSet<DeviceType> DeviceTypes { get; set; }

    public virtual DbSet<FcmToken> FcmTokens { get; set; }

    public virtual DbSet<RefreshToken> RefreshTokens { get; set; }

    public virtual DbSet<TelemetryLog> TelemetryLogs { get; set; }

    public virtual DbSet<UserDevice> UserDevices { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.UseCollation("Latin1_General_100_CI_AS_SC");

        modelBuilder.Entity<Alarm>(entity =>
        {
            entity.HasIndex(e => e.CreatedAtUtc, "IX_Alarms_CreatedAtUtc").IsDescending();

            entity.HasIndex(e => e.DeviceId, "IX_Alarms_DeviceId");

            entity.Property(e => e.CreatedAtUtc)
                .HasPrecision(0)
                .HasDefaultValueSql("(sysutcdatetime())", "DF_Alarms_CreatedAtUtc");
            entity.Property(e => e.Description)
                .IsRequired()
                .HasMaxLength(500);
            entity.Property(e => e.Type)
                .IsRequired()
                .HasMaxLength(50);

            entity.HasOne(d => d.Device).WithMany(p => p.Alarms)
                .HasForeignKey(d => d.DeviceId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Alarms_Devices");
        });

        modelBuilder.Entity<AlarmRead>(entity =>
        {
            entity.HasIndex(e => e.AlarmId, "IX_AlarmReads_AlarmId");

            entity.HasIndex(e => e.UserId, "IX_AlarmReads_UserId");

            entity.HasIndex(e => new { e.AlarmId, e.UserId }, "UQ_AlarmReads").IsUnique();

            entity.Property(e => e.DismissedAtUtc).HasPrecision(0);
            entity.Property(e => e.ReadAtUtc)
                .HasPrecision(0)
                .HasDefaultValueSql("(sysutcdatetime())", "DF_AlarmReads_ReadAtUtc");
            entity.Property(e => e.UserId).IsRequired();

            entity.HasOne(d => d.Alarm).WithMany(p => p.AlarmReads)
                .HasForeignKey(d => d.AlarmId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_AlarmReads_Alarms");

            entity.HasOne(d => d.User).WithMany(p => p.AlarmReads)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_AlarmReads_AspNetUsers");
        });

        modelBuilder.Entity<AspNetUser>(entity =>
        {
            entity.ToTable("AspNetUsers", "identity");

            entity.HasIndex(e => e.NormalizedEmail, "EmailIndex");

            entity.HasIndex(e => e.NormalizedUserName, "UserNameIndex")
                .IsUnique()
                .HasFilter("([NormalizedUserName] IS NOT NULL)");

            entity.Property(e => e.Email).HasMaxLength(256);
            entity.Property(e => e.NormalizedEmail).HasMaxLength(256);
            entity.Property(e => e.NormalizedUserName).HasMaxLength(256);
            entity.Property(e => e.UserName).HasMaxLength(256);
        });

        modelBuilder.Entity<BatteryType>(entity =>
        {
            entity.HasIndex(e => e.Name, "UQ_BatteryTypes_Name").IsUnique();

            entity.HasIndex(e => e.IsDefault, "UX_BatteryTypes_IsDefault")
                .IsUnique()
                .HasFilter("([IsDefault]=(1))");

            entity.Property(e => e.ChargingMinV)
                .HasColumnType("decimal(5, 2)")
                .HasColumnName("ChargingMin_V");
            entity.Property(e => e.GoodMinV)
                .HasColumnType("decimal(5, 2)")
                .HasColumnName("GoodMin_V");
            entity.Property(e => e.LowMinV)
                .HasColumnType("decimal(5, 2)")
                .HasColumnName("LowMin_V");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(50);
        });

        modelBuilder.Entity<ChlorinatorBattery>(entity =>
        {
            entity.ToTable("ChlorinatorBattery");

            entity.HasIndex(e => new { e.DeviceId, e.TsUtc }, "IX_ChlorinatorBattery_DeviceId_TsUtc").IsDescending(false, true);

            entity.Property(e => e.CreatedAtUtc)
                .HasPrecision(0)
                .HasDefaultValueSql("(sysutcdatetime())", "DF_ChlorinatorBattery_CreatedAtUtc");
            entity.Property(e => e.TriggerType)
                .IsRequired()
                .HasMaxLength(20)
                .HasDefaultValue("auto", "DF_ChlorinatorBattery_TriggerType");
            entity.Property(e => e.TsUtc).HasPrecision(0);
            entity.Property(e => e.VoltageV)
                .HasColumnType("decimal(5, 2)")
                .HasColumnName("Voltage_V");

            entity.HasOne(d => d.Device).WithMany(p => p.ChlorinatorBatteries)
                .HasForeignKey(d => d.DeviceId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ChlorinatorBattery_Device");
        });

        modelBuilder.Entity<ChlorinatorConfig>(entity =>
        {
            entity.HasKey(e => e.DeviceId);

            entity.ToTable("ChlorinatorConfig");

            entity.Property(e => e.DeviceId).ValueGeneratedNever();
            entity.Property(e => e.EmptyDistanceMm).HasColumnName("EmptyDistance_mm");
            entity.Property(e => e.FullDistanceMm).HasColumnName("FullDistance_mm");
            entity.Property(e => e.UpdatedAtUtc)
                .HasPrecision(0)
                .HasDefaultValueSql("(sysutcdatetime())", "DF_ChlorinatorConfig_UpdatedAtUtc");

            entity.HasOne(d => d.BatteryType).WithMany(p => p.ChlorinatorConfigs)
                .HasForeignKey(d => d.BatteryTypeId)
                .HasConstraintName("FK_ChlorinatorConfig_BatteryType");

            entity.HasOne(d => d.Device).WithOne(p => p.ChlorinatorConfig)
                .HasForeignKey<ChlorinatorConfig>(d => d.DeviceId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ChlorinatorConfig_Device");
        });

        modelBuilder.Entity<ChlorinatorDailySummary>(entity =>
        {
            entity.ToTable("ChlorinatorDailySummary");

            entity.HasIndex(e => new { e.DeviceId, e.Day }, "UQ_ChlorinatorDailySummary_DeviceId_Day").IsUnique();

            entity.Property(e => e.UpdatedAtUtc)
                .HasPrecision(0)
                .HasDefaultValueSql("(sysutcdatetime())", "DF_ChlorinatorDailySummary_UpdatedAtUtc");

            entity.HasOne(d => d.Device).WithMany(p => p.ChlorinatorDailySummaries)
                .HasForeignKey(d => d.DeviceId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ChlorinatorDailySummary_Device");
        });

        modelBuilder.Entity<ChlorinatorDose>(entity =>
        {
            entity.ToTable("ChlorinatorDose");

            entity.HasIndex(e => new { e.DeviceId, e.TsUtc }, "IX_ChlorinatorDose_DeviceId_TsUtc").IsDescending(false, true);

            entity.Property(e => e.CreatedAtUtc)
                .HasPrecision(0)
                .HasDefaultValueSql("(sysutcdatetime())", "DF_ChlorinatorDose_CreatedAtUtc");
            entity.Property(e => e.TriggerType).HasMaxLength(20);
            entity.Property(e => e.TsUtc).HasPrecision(0);

            entity.HasOne(d => d.Device).WithMany(p => p.ChlorinatorDoses)
                .HasForeignKey(d => d.DeviceId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ChlorinatorDose_Device");
        });

        modelBuilder.Entity<ChlorinatorLevel>(entity =>
        {
            entity.ToTable("ChlorinatorLevel");

            entity.HasIndex(e => new { e.DeviceId, e.TsUtc }, "IX_ChlorinatorLevel_DeviceId_TsUtc").IsDescending(false, true);

            entity.Property(e => e.CreatedAtUtc)
                .HasPrecision(0)
                .HasDefaultValueSql("(sysutcdatetime())", "DF_ChlorinatorLevel_CreatedAtUtc");
            entity.Property(e => e.DistanceMm).HasColumnName("Distance_mm");
            entity.Property(e => e.TriggerType)
                .IsRequired()
                .HasMaxLength(20)
                .HasDefaultValue("auto", "DF_ChlorinatorLevel_TriggerType");
            entity.Property(e => e.TsUtc).HasPrecision(0);

            entity.HasOne(d => d.Device).WithMany(p => p.ChlorinatorLevels)
                .HasForeignKey(d => d.DeviceId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ChlorinatorLevel_Device");
        });

        modelBuilder.Entity<Device>(entity =>
        {
            entity.HasKey(e => e.DeviceId).HasName("PK_Device");

            entity.HasIndex(e => e.MacAddress, "UX_Device_MacAddress").IsUnique();

            entity.Property(e => e.DeviceId).HasDefaultValueSql("(newid())", "DF_Device_DeviceId");
            entity.Property(e => e.IsEnabled).HasDefaultValue(true, "DF_Device_IsEnable");
            entity.Property(e => e.MacAddress)
                .IsRequired()
                .HasMaxLength(12)
                .IsUnicode(false)
                .IsFixedLength();
            entity.Property(e => e.MqttCredential)
                .HasMaxLength(500)
                .IsUnicode(false);
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.ProvisioningExpiresAtUtc).HasPrecision(0);
            entity.Property(e => e.Readings)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.RegisteredAtUtc)
                .HasPrecision(0)
                .HasDefaultValueSql("(sysutcdatetime())", "DF_Device_RegisteredAtUtc");
            entity.Property(e => e.RegisteredByUserId)
                .IsRequired()
                .HasMaxLength(450);

            entity.HasOne(d => d.DeviceType).WithMany(p => p.Devices)
                .HasForeignKey(d => d.DeviceTypeId)
                .HasConstraintName("FK_Devices_DeviceType");

            entity.HasOne(d => d.RegisteredByUser).WithMany(p => p.Devices)
                .HasForeignKey(d => d.RegisteredByUserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Device_AspNetUsers_RegisteredBy");
        });

        modelBuilder.Entity<DeviceType>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__DeviceTy__3214EC07D0000D4E");

            entity.HasIndex(e => e.Name, "UQ_DeviceTypes_Name").IsUnique();

            entity.Property(e => e.Description).HasMaxLength(200);
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.TelemetrySp).HasMaxLength(100);
        });

        modelBuilder.Entity<FcmToken>(entity =>
        {
            entity.HasIndex(e => e.UserId, "IX_FcmTokens_UserId");

            entity.HasIndex(e => e.Token, "UQ_FcmTokens_Token").IsUnique();

            entity.Property(e => e.CreatedAtUtc)
                .HasPrecision(0)
                .HasDefaultValueSql("(sysutcdatetime())", "DF_FcmTokens_CreatedAtUtc");
            entity.Property(e => e.LastUsedAtUtc)
                .HasPrecision(0)
                .HasDefaultValueSql("(sysutcdatetime())", "DF_FcmTokens_LastUsedAtUtc");
            entity.Property(e => e.Token)
                .IsRequired()
                .HasMaxLength(500);
            entity.Property(e => e.UserId).IsRequired();

            entity.HasOne(d => d.User).WithMany(p => p.FcmTokens)
                .HasForeignKey(d => d.UserId)
                .HasConstraintName("FK_FcmTokens_AspNetUsers");
        });

        modelBuilder.Entity<RefreshToken>(entity =>
        {
            entity.HasIndex(e => e.UserId, "IX_RefreshTokens_UserId");

            entity.HasIndex(e => e.Token, "UQ_RefreshTokens_Token").IsUnique();

            entity.Property(e => e.CreatedAtUtc)
                .HasPrecision(0)
                .HasDefaultValueSql("(sysutcdatetime())", "DF_RefreshTokens_CreatedAtUtc");
            entity.Property(e => e.ExpiresAtUtc).HasPrecision(0);
            entity.Property(e => e.RevokedAtUtc).HasPrecision(0);
            entity.Property(e => e.Token)
                .IsRequired()
                .HasMaxLength(500);
            entity.Property(e => e.UserId).IsRequired();

            entity.HasOne(d => d.User).WithMany(p => p.RefreshTokens)
                .HasForeignKey(d => d.UserId)
                .HasConstraintName("FK_RefreshTokens_AspNetUsers");
        });

        modelBuilder.Entity<TelemetryLog>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Telemetr__3214EC07D1A9E0D4");

            entity.ToTable("TelemetryLog");

            entity.HasIndex(e => e.Processed, "IX_TelemetryLog_Processed");

            entity.HasIndex(e => e.ReceivedAtUtc, "IX_TelemetryLog_ReceivedAtUtc").IsDescending();

            entity.Property(e => e.ErrorMessage).HasMaxLength(2000);
            entity.Property(e => e.Payload).IsRequired();
            entity.Property(e => e.ReceivedAtUtc).HasDefaultValueSql("(getutcdate())");
            entity.Property(e => e.Topic)
                .IsRequired()
                .HasMaxLength(500);
        });

        modelBuilder.Entity<UserDevice>(entity =>
        {
            entity.HasIndex(e => new { e.UserId, e.DeviceId }, "UQ_UserDevices_User_Device").IsUnique();

            entity.Property(e => e.UserId).IsRequired();

            entity.HasOne(d => d.Device).WithMany(p => p.UserDevices)
                .HasForeignKey(d => d.DeviceId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_UserDevices_Devices");

            entity.HasOne(d => d.User).WithMany(p => p.UserDevices)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_UserDevices_AspNetUsers");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}